// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGwCrTlvCkWyLx0XiTPqgN0dC8Y2c1nag',
    appId: '1:641006812551:web:be426808eb4302a1d76722',
    messagingSenderId: '641006812551',
    projectId: 'event-planner-1540f',
    authDomain: 'event-planner-1540f.firebaseapp.com',
    storageBucket: 'event-planner-1540f.firebasestorage.app',
    measurementId: 'G-086GQ025JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjNIrM4tdfI7xAME09qrJy2ttumIGK5cU',
    appId: '1:641006812551:android:737ef449a1e42828d76722',
    messagingSenderId: '641006812551',
    projectId: 'event-planner-1540f',
    storageBucket: 'event-planner-1540f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5h44SQeRoDgv3hSiShKpW36xC96ATD6g',
    appId: '1:641006812551:ios:9f5c502c304dc62ed76722',
    messagingSenderId: '641006812551',
    projectId: 'event-planner-1540f',
    storageBucket: 'event-planner-1540f.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5h44SQeRoDgv3hSiShKpW36xC96ATD6g',
    appId: '1:641006812551:ios:9f5c502c304dc62ed76722',
    messagingSenderId: '641006812551',
    projectId: 'event-planner-1540f',
    storageBucket: 'event-planner-1540f.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGwCrTlvCkWyLx0XiTPqgN0dC8Y2c1nag',
    appId: '1:641006812551:web:15658e62554a8838d76722',
    messagingSenderId: '641006812551',
    projectId: 'event-planner-1540f',
    authDomain: 'event-planner-1540f.firebaseapp.com',
    storageBucket: 'event-planner-1540f.firebasestorage.app',
    measurementId: 'G-PN1J99CVSJ',
  );
}
